apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checkout-service.fullname" . }}
  labels:
    {{- include "checkout-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "checkout-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "checkout-service.labels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      dnsPolicy: {{ .Values.dnsPolicy | default "ClusterFirst" }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}

      containers:
        - name: checkout-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python3
            - -u
            - /app/app.py
          env:
            - name: MODE
              value: {{ .Values.config.mode | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.config.postgresHost | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.config.postgresPort | quote }}
            - name: STRIPE_HOST
              value: {{ .Values.config.stripeHost | quote }}
            - name: STRIPE_PORT
              value: {{ .Values.config.stripePort | quote }}
            - name: CONCURRENCY
              value: {{ .Values.config.concurrency | quote }}
            - name: REQUEST_TIMEOUT
              value: {{ .Values.config.requestTimeout | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          configMap:
            name: {{ include "checkout-service.fullname" . }}-code
            defaultMode: 0755
